config/routes.rb
Rails.application.routes.draw do

  resources :stations
  resources :properties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :stations
  #accepts_nested_attributes_for :stations
  accepts_nested_attributes_for :stations, :allow_destroy => true
  #accepts_nested_attributes_for :stations, reject_if: :all_blank
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update,:destroy ]
  def index
    @properties = Property.all
  end

  def new
    if params[:back]
      @property = Property.new(property_params)
    else
      @property = Property.new
      2.times { @property.stations.build }
    end
  end

  def create
    @property = Property.new(property_params)
    if params[:back]
      render :new
    else
        if @property.save
          redirect_to properties_path, notice: "creation de proprité"
        else
          render :new
        end
    end
  end

  def show
  end

  def edit
  end

  def destroy
    if @property.delete
      flash[:notice] = 'station deleted!'
      redirect_to properties_path
    else
      flash[:error] = 'Failed to delete this property!'
      render :destroy
    end
  end

  def update
      # Overlap!
    if @property.update(property_params)
      redirect_to properties_path, notice: "I edited the property!"
    else
      render :edit
    end
  end
  private
  def property_params
    params.require(:property).permit(:propertyName, :rent, :railName, :buildAge, :address, :note, stations_attributes:{} )
  end
  def set_property
    @property = Property.find(params[:id])
    #@property = Property.find_by_id(params[:property_id])
  end
  def test
  end 
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
    <% if @property.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>
        <ul>
        <% property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="station_form">

        <%= f.fields_for :properties do |near| %>

          <%= f.label :propertyName %><br>
        <%= f.text_field :propertyName %><br>
          <%= f.label :rent %><br><%= f.text_field :rent %><br>
        

        <%= f.label :building_Age %><br>
        <%= f.text_field :buildAge %><br>
        <%= f.label :address %><br><%= f.text_area :address %><br>
        <%= f.label :Remark %><br><%= f.text_area :note%><br>

        <% end %>
</div>

          <hr>
          <div class="station_form">
    <% n = 0 %>
    <%= f.fields_for :stations do |near| %>
      <h2>Nearest station<%= n += 1 %></h2>
      <%= near.label :stationName %><br>
      <%= near.text_field :stationName %><br>
      <%= near.label :timeWalk %><br>
      <%= near.text_field :timeWalk %><br>
      <%= near.label :railName %><br>
      <%= near.text_field :railName %><br>
    <% end %>
  </div>
          <div class="actions">
            <%= f.submit value:"Register"%>
          </div>
    </div>
    <%= link_to "Retour ", properties_path %>
  <% end %>

app/views/properties/_form1.html.erb
<%= form_for(@property) do |f| %>
    <% if @property.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

        <ul>
        <% property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="container">


          <div class="field">
            <%= f.label :propertyName %>
            <%= f.text_field :propertyName %>
          </div>

          <div class="field">
            <%= f.label :rent %>
            <%= f.text_field :rent %>
          </div>

          <div class="field">
            <%= f.label :railName %>
            <%= f.text_field :railName %>
          </div>

          <div class="field">
            <%= f.label :buildAge %>
            <%= f.text_field :buildAge %>
          </div>

          <div class="field">
            <%= f.label :address %>
            <%= f.text_area :address %>
          </div>
          <hr>

          <div class="field">
            <%= f.label :note %>
            <%= f.text_field :note %>
          </div>

          <div class="actions">
            <%= f.submit value:"Register"%>
          </div>

    </div>
    <%= link_to "Retour ", properties_path %>
  <% end %>

app/views/properties/destroy.html.erb
<h1>Properties#destroy</h1>
<p>Find me in app/views/properties/destroy.html.erb</p>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>


<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/edit1.html.erb
<%= form_with(model: Property.new) do |form| %>

  <div class="Property_Name">
    <%= form.label :Property %>
    <%= form.text_field :propertyName %>
  </div>
  <div class="property_rent">
    <%= form.label :Rent %>
    <%= form.text_field :rent %>
  </div>
  <div class="property_rail">
    <%= form.label :RailName %>
    <%= form.text_field :railName %>
  </div>
  <div class="property_age">
    <%= form.label :Age %>
    <%= form.text_field :buildAge %>
  </div>
  <div class="property_address">
    <%= form.label :Addresse %>
    <%= form.text_field :address %>
  </div>
  <div class="property_note">
    <%= form.label :note %>
    <%= form.text_field :note %>
  </div>
  <%= form.submit %>
<% end %>

app/views/properties/index.html.erb
<h1>Property list</h1>
<table>
  <tr>
    <th>Property</th>
    <th>Rent</th>
    <th>Address</th>
    <th>Building Age</th>
    <th>Remark</th>
  </tr>
<% @properties.each do |property| %>

  <tr>
    <td><%= property.propertyName %></td>
    <td><%= property.rent %></td>
    <td><%= property.address %></td>
    <td><%= property.buildAge %></td>
    <td><%= property.note %></td>
    <td><%= link_to 'Check the details', property_path(property.id) %></td>
    <td><%= link_to "Edit property", edit_property_path(property.id) %></td>
    <td><%= link_to 'supprimer', property_path(property.id), method: :delete ,data: { confirm: 'voulez vous supprimer？' } %></td>

  </tr>
<% end %>

</table>
<br>
<%= link_to 'Post a new property', new_property_path %>

app/views/properties/new.html.erb
<h2>Register Property</h2>


<%= render 'form' %>

app/views/properties/new1.html.erb
<%= form_with(model: Property.new) do |form| %>

<% if @property.errors.any? %>
   <div id="error_explanation">
     <h2><%= @property.errors.count %>件のエラーがあります。</h2>
     <ul>
     <% @property.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
 <% end %>


  <div class="Property_Name">
    <%= form.label :Property %>
    <%= form.text_field :propertyName %>
  </div>
  <div class="property_rent">
    <%= form.label :Rent %>
    <%= form.text_field :rent %>
  </div>
  <div class="property_rail">
    <%= form.label :RailName %>
    <%= form.text_field :railName %>
  </div>
  <div class="property_age">
    <%= form.label :Age %>
    <%= form.text_field :buildAge %>
  </div>
  <div class="property_address">
    <%= form.label :Addresse %>
    <%= form.text_field :address %>
  </div>
  <div class="property_note">
    <%= form.label :note %>
    <%= form.text_field :note %>

 <%= fields_for :stations do |station| %>
     <div class="station_name">
      <%= station.label :station  %>
      <%= station.text_field :stationName %>
      <div class="time_walk">
      <%= station.label :Time %>
      <%= station.text_field :timeWalk %>
      <div class="">
      <%= station.label :Rails %>
      <%= station.text_field :railName %>
      <% end %>


  </div>
  <%= form.submit %>
<% end %>

app/views/properties/show.html.erb
<h1>Détails des properties</h1>
<div>
  <p>Property Name: <%= @property.propertyName %></p>
  <p>Rent : <%= @property.rent %></p>
  <p>Adress: <%= @property.address %></p>
  <p>Building Age: <%= @property.buildAge %></p>
  <p>Remark: <%= @property.note%></p>
</div>

<div>
  <% n = 0 %>
  <% @property.stations.each do |station| %>
    <h2>Nearest station<%= n += 1 %></h2>
      <p>
        <strong>stationName:</strong><%= station.stationName %>
      </p>
      <p>
        <strong>stationName:</strong><%= station.timeWalk %>
      </p>
      <p>
        <strong>stationName:</strong><%= station.railName %>
      </p>
  <% end %>
</div>

<%= link_to 'edit', edit_property_path %> |
<%= link_to 'back', properties_path %>

app/views/properties/update.html.erb
<h1>Properties#update</h1>
<p>Find me in app/views/properties/update.html.erb</p>